#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppGeoFit.Droid.Resource", IsApplication=true)]

namespace AppGeoFit.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Captain = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Edit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int exclamation_error = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Plus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Trash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int ChangeIpTextL = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int ColorElement_imageColor = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ColorElement_nameColor = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int ColorList_list = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int CreateTeam_AceptButton = 2131099666;
			
			// aapt resource value: 0x7f060019
			public const int CreateTeam_CancelButton = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int CreateTeam_ColorButton = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int CreateTeam_LabelColor = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int CreateTeam_LabelName = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int CreateTeam_LabelSport = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int CreateTeam_Name = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int CreateTeam_SpinnerSport = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int CreateTeam_imageColor = 2131099670;
			
			// aapt resource value: 0x7f06000e
			public const int CreateTeam_relativeLayout1 = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int CreateTeam_relativeLayoutColor = 2131099669;
			
			// aapt resource value: 0x7f06000d
			public const int CreateTeam_text = 2131099661;
			
			// aapt resource value: 0x7f060068
			public const int CtxLstDelete = 2131099752;
			
			// aapt resource value: 0x7f060067
			public const int CtxLstProfile = 2131099751;
			
			// aapt resource value: 0x7f06001f
			public const int D_SPlayer_addButton = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int D_SPlayer_cancelButton = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int D_SPlayer_playerToFind = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int D_SPlayer_textView1 = 2131099677;
			
			// aapt resource value: 0x7f060027
			public const int Edit_AceptButton = 2131099687;
			
			// aapt resource value: 0x7f06002f
			public const int Edit_CancelButton = 2131099695;
			
			// aapt resource value: 0x7f06002d
			public const int Edit_Email = 2131099693;
			
			// aapt resource value: 0x7f060025
			public const int Edit_LabelEmail = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int Edit_LabelFavoriteSport = 2131099686;
			
			// aapt resource value: 0x7f060022
			public const int Edit_LabelLastName = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int Edit_LabelName = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int Edit_LabelNick = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int Edit_LabelPhoneNumber = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int Edit_LastName = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int Edit_Name = 2131099689;
			
			// aapt resource value: 0x7f06002b
			public const int Edit_Nick = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int Edit_PhoneNumber = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int Edit_SpinnerFavoriteSport = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int ElementPlayerList_Nick = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int ElementPlayerList_RatingBar = 2131099697;
			
			// aapt resource value: 0x7f060042
			public const int Email = 2131099714;
			
			// aapt resource value: 0x7f06003a
			public const int LabelEmail = 2131099706;
			
			// aapt resource value: 0x7f060037
			public const int LabelLastName = 2131099703;
			
			// aapt resource value: 0x7f06003c
			public const int LabelMedOnTime = 2131099708;
			
			// aapt resource value: 0x7f060036
			public const int LabelName = 2131099702;
			
			// aapt resource value: 0x7f060038
			public const int LabelNick = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int LabelPhoneNumber = 2131099705;
			
			// aapt resource value: 0x7f06003b
			public const int LabelRating = 2131099707;
			
			// aapt resource value: 0x7f06003f
			public const int LastName = 2131099711;
			
			// aapt resource value: 0x7f060044
			public const int MedOnTime = 2131099716;
			
			// aapt resource value: 0x7f06003e
			public const int Name = 2131099710;
			
			// aapt resource value: 0x7f060040
			public const int Nick = 2131099712;
			
			// aapt resource value: 0x7f060002
			public const int NickOrEmailText = 2131099650;
			
			// aapt resource value: 0x7f060041
			public const int PhoneNumber = 2131099713;
			
			// aapt resource value: 0x7f060034
			public const int PlayerProfileL = 2131099700;
			
			// aapt resource value: 0x7f06005c
			public const int RelativeLayout1 = 2131099740;
			
			// aapt resource value: 0x7f06005f
			public const int RelativeLayout2 = 2131099743;
			
			// aapt resource value: 0x7f060005
			public const int SignInButton = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int SignUpTextL = 2131099654;
			
			// aapt resource value: 0x7f060051
			public const int SignUp_AceptButton = 2131099729;
			
			// aapt resource value: 0x7f06005a
			public const int SignUp_CancelButton = 2131099738;
			
			// aapt resource value: 0x7f060058
			public const int SignUp_Email = 2131099736;
			
			// aapt resource value: 0x7f06004f
			public const int SignUp_LabelEmail = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int SignUp_LabelFavoriteSport = 2131099728;
			
			// aapt resource value: 0x7f06004c
			public const int SignUp_LabelLastName = 2131099724;
			
			// aapt resource value: 0x7f060049
			public const int SignUp_LabelName = 2131099721;
			
			// aapt resource value: 0x7f06004d
			public const int SignUp_LabelNick = 2131099725;
			
			// aapt resource value: 0x7f06004a
			public const int SignUp_LabelPassword = 2131099722;
			
			// aapt resource value: 0x7f06004e
			public const int SignUp_LabelPhoneNumber = 2131099726;
			
			// aapt resource value: 0x7f06004b
			public const int SignUp_LabelRepeatPassword = 2131099723;
			
			// aapt resource value: 0x7f060055
			public const int SignUp_LastName = 2131099733;
			
			// aapt resource value: 0x7f060052
			public const int SignUp_Name = 2131099730;
			
			// aapt resource value: 0x7f060056
			public const int SignUp_Nick = 2131099734;
			
			// aapt resource value: 0x7f060053
			public const int SignUp_Password = 2131099731;
			
			// aapt resource value: 0x7f060057
			public const int SignUp_PhoneNumber = 2131099735;
			
			// aapt resource value: 0x7f060054
			public const int SignUp_RepeatPassword = 2131099732;
			
			// aapt resource value: 0x7f060059
			public const int SignUp_SpinnerFavoriteSport = 2131099737;
			
			// aapt resource value: 0x7f060047
			public const int SignUp_linearLayout1 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int SignUp_relativeLayout1 = 2131099720;
			
			// aapt resource value: 0x7f060013
			public const int SignUp_relativeLayout2 = 2131099667;
			
			// aapt resource value: 0x7f060046
			public const int SignUp_textView1 = 2131099718;
			
			// aapt resource value: 0x7f060066
			public const int Team_addPlayerButton = 2131099750;
			
			// aapt resource value: 0x7f06005e
			public const int Team_captainName = 2131099742;
			
			// aapt resource value: 0x7f060061
			public const int Team_createTeamB = 2131099745;
			
			// aapt resource value: 0x7f06005b
			public const int Team_deleteTeamButton = 2131099739;
			
			// aapt resource value: 0x7f060060
			public const int Team_editTeamButton = 2131099744;
			
			// aapt resource value: 0x7f060064
			public const int Team_gamesListView = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int Team_playerListView = 2131099749;
			
			// aapt resource value: 0x7f060063
			public const int Team_spinnerTeams = 2131099747;
			
			// aapt resource value: 0x7f06005d
			public const int Team_teamName = 2131099741;
			
			// aapt resource value: 0x7f060033
			public const int Toolbar_spinnerSports = 2131099699;
			
			// aapt resource value: 0x7f06001a
			public const int actualIp = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int buttonChangeIp = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int editIp = 2131099675;
			
			// aapt resource value: 0x7f06003d
			public const int imageButtonDelete = 2131099709;
			
			// aapt resource value: 0x7f060035
			public const int imageButtonEdit = 2131099701;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout1 = 2131099659;
			
			// aapt resource value: 0x7f060062
			public const int linearLayout2 = 2131099746;
			
			// aapt resource value: 0x7f060069
			public const int menu_settings = 2131099753;
			
			// aapt resource value: 0x7f060004
			public const int passwordText = 2131099652;
			
			// aapt resource value: 0x7f060043
			public const int ratingBar = 2131099715;
			
			// aapt resource value: 0x7f060045
			public const int ratingBar1 = 2131099717;
			
			// aapt resource value: 0x7f060008
			public const int relativeLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060028
			public const int relativeLayout2 = 2131099688;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView3 = 2131099651;
			
			// aapt resource value: 0x7f060032
			public const int toolbarPrincipal = 2131099698;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Authentication = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ColorElement = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ColorList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateTeam = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_ip = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_SearchPlayer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EditPlayer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ElementPlayerList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MainActivity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MainToolbar = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PlayerProfile = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PlayerTeamList = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SignUp = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SimpleToolbar = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Team = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MenuPlayerList = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MenuPlayerListNoC = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int principalMenu = 2131034114;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int MyTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
